name: Deploy WASM emulator to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Assemble site
      run: |
        cd wasm
        wasm-pack build --release --target web --out-dir web/wasm
        cd ..
        mkdir -p site
        cp -r wasm/web/* site/

    - uses: actions/upload-pages-artifact@v3
      with:
        path: site
        name: github-pages-${{ github.run_id }}

    - uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ github.run_id }}
